resources:
- name: music-repo
  type: git
  source:
    uri: https://github.com/VarunRaisinghani/hello-spring-cloud.git
    branch: master
- name: cf
  type: cf
  source:
    api: https://donotuseapi.run.pivotal.io
    username: vraisinghani@pivotal.io
    password: Jun2@191
    organization: cloudnative-varun
    space: development
    skip_cert_check: true
jobs:
  - name: maven-package
    plan:
    - get: music-repo
      trigger: true
    - task: maven-package
      privileged: true
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: maven}
        inputs:
          - name: music-repo
        outputs:
          - name: build
        # caches:
        #   - path: repo/m2
        run:
          path: bash
          args:
          - -c
          - |
            set -e
            cd music-repo
            mvn package -DskipTests=true
            mv target/hello-spring-cloud-0.0.1.BUILD-SNAPSHOT.jar ../build
    - put: cf
      params:
        manifest: music-repo/manifest.yml
        path: build/hello-spring-cloud-0.0.1.BUILD-SNAPSHOT.jar
